-- Client chrome source-contract tests (EPIC 44, harborheist-kqbq).
--
-- init.client.lua cannot be required under lune (Instance/game at top
-- level), so these specs assert the production source still contains the
-- motion/feedback invariants landed by EPIC 44 children. Pure source
-- contracts only — visual confirmation lives in the Studio passes
-- (harborheist-orpl / harborheist-rswb).
--
-- kqbq.1 contracts ACTIVATED 2026-08-01: all four close sites verified at 0.22s.
-- kqbq.2 contracts ACTIVATED 2026-08-01: EASE_PRESS 0.10s, depth 0.94.
-- kqbq.3 contracts ACTIVATED 2026-08-01: EASE_HOVER 0.2s for all hover tweens.
-- kqbq.5 contracts ACTIVATED 2026-08-01: toast accent bar 6px + soft glow frame.
-- kqbq.6 contracts ACTIVATED 2026-08-01: marker glow 18px / 0.50 transparency.
-- kqbq.9 contracts ACTIVATED 2026-08-01: mobile scrollbar auto-hide on idle.
-- kqbq.7 contracts ACTIVATED 2026-08-01: cast overlay zone micro-labels.
-- kqbq.8 contracts ACTIVATED 2026-08-01: mobile action-stack scroll affordance.
-- kqbq.11 contracts ACTIVATED 2026-08-01: HUD income-line split labels (kill 5Hz RichText rebuild).

local fs = require("@lune/fs")

local clientSource = fs.readFile("src/client/init.client.lua")

return function(describe, it, expect)
describe("EPIC 44 client chrome source contracts", function()
	it("spec harness loads and client source is readable", function()
		expect(#clientSource > 1000).to.equal(true)
	end)

	describe("kqbq.1 panel close/open duration harmony", function()
		it("hidePanels mobile slides down at 0.22s", function()
			expect(clientSource:find('Anim:slide(panel, "down", 0.22)', 1, true)).to.be.a("number")
		end)
		it("hidePanels desktop scales to 0.9 at 0.22s", function()
			expect(clientSource:find("Anim:scale(panel, fit * 0.9, 0.22)", 1, true)).to.be.a("number")
		end)
		it("showPanel switch mobile slides oldPanel down at 0.22s", function()
			expect(clientSource:find('Anim:slide(oldPanel, "down", 0.22)', 1, true)).to.be.a("number")
		end)
		it("showPanel switch desktop scales oldPanel to 0.9 at 0.22s", function()
			expect(clientSource:find("Anim:scale(oldPanel, fit * 0.9, 0.22)", 1, true)).to.be.a("number")
		end)
		it("no 0.16s close duration remains on slide-down paths", function()
			expect(clientSource:find('"down", 0.16', 1, true) == nil).to.equal(true)
		end)
		it("no 0.16s close duration remains on scale-to-0.9 paths", function()
			expect(clientSource:find("fit * 0.9, 0.16", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.2 button press feel", function()
		it("EASE_PRESS preset defined at 0.10s Quad Out", function()
			expect(clientSource:find("EASE_PRESS = TweenInfo.new(0.10, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)", 1, true)).to.be.a("number")
		end)
		it("pressTween uses EASE_PRESS", function()
			expect(clientSource:find("pressTween = EASE_PRESS", 1, true)).to.be.a("number")
		end)
		it("press compression depth is 0.94", function()
			expect(clientSource:find("pressTween, { Scale = 0.94 }", 1, true)).to.be.a("number")
		end)
		it("release still uses EASE_POP (Spring)", function()
			expect(clientSource:find("EASE_POP, { Scale = 1 }", 1, true)).to.be.a("number")
		end)
		it("EASE_PRESS defined exactly once", function()
			local count = 0
			for _ in clientSource:gmatch("EASE_PRESS") do count = count + 1 end
			expect(count).to.equal(2) -- definition + usage at pressTween
		end)
	end)

	describe("kqbq.3 desktop hover pacing", function()
		it("EASE_HOVER preset defined at 0.2s Quad Out", function()
			expect(clientSource:find("EASE_HOVER = TweenInfo.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)", 1, true)).to.be.a("number")
		end)
		it("hover scale-up uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { Scale = 1.02 }", 1, true)).to.be.a("number")
		end)
		it("hover color tween uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundColor3 = hoverColor }", 1, true)).to.be.a("number")
		end)
		it("hover glow uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundTransparency = 0.9 }", 1, true)).to.be.a("number")
		end)
		it("hover shadow fade-in uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundTransparency = targetAlpha }", 1, true)).to.be.a("number")
		end)
		it("leave scale-back uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { Scale = 1 }", 1, true)).to.be.a("number")
		end)
		it("leave color restore uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundColor3 = originalColor }", 1, true)).to.be.a("number")
		end)
		it("leave glow hide uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundTransparency = 1 }", 1, true)).to.be.a("number")
		end)
		it("press path does NOT use EASE_HOVER", function()
			expect(clientSource:find("pressTween = EASE_HOVER", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.5 toast accent bar strengthening", function()
		it("accent bar widened to 6px", function()
			expect(clientSource:find("accentBar.Size = UDim2.new(0, 6, 1, -14)", 1, true)).to.be.a("number")
		end)
		it("accent glow frame exists at ZIndex 56", function()
			expect(clientSource:find("accentGlow.ZIndex = 56", 1, true)).to.be.a("number")
		end)
		it("accent glow is 10px wide", function()
			expect(clientSource:find("accentGlow.Size = UDim2.new(0, 10, 1, -10)", 1, true)).to.be.a("number")
		end)
		it("accent glow fade-in targets 0.85", function()
			expect(clientSource:find("accentGlow, EASE_OUT, { BackgroundTransparency = 0.85 }", 1, true)).to.be.a("number")
		end)
		it("accent glow fade-out targets 1", function()
			expect(clientSource:find("accentGlow, fade, { BackgroundTransparency = 1 }", 1, true)).to.be.a("number")
		end)
		it("no 4px accent bar remains", function()
			expect(clientSource:find("accentBar.Size = UDim2.new(0, 4, 1, -14)", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.6 marker glow brightening", function()
		it("cast/raid marker glow is 18px wide", function()
			expect(clientSource:find("markerGlow.Size = UDim2.new(0, 18, 1, 10)", 1, true)).to.be.a("number")
		end)
		it("cast/raid marker glow transparency is 0.50", function()
			expect(clientSource:find("markerGlow.BackgroundTransparency = 0.50", 1, true)).to.be.a("number")
		end)
		it("bite marker glow is 18px wide", function()
			expect(clientSource:find("biteMarkerGlow.Size = UDim2.new(0, 18, 1, 10)", 1, true)).to.be.a("number")
		end)
		it("bite marker glow transparency is 0.50", function()
			expect(clientSource:find("biteMarkerGlow.BackgroundTransparency = 0.50", 1, true)).to.be.a("number")
		end)
		it("no 0.75 transparency remains on markerGlow", function()
			expect(clientSource:find("markerGlow.BackgroundTransparency = 0.75", 1, true) == nil).to.equal(true)
		end)
		it("no 0.75 transparency remains on biteMarkerGlow", function()
			expect(clientSource:find("biteMarkerGlow.BackgroundTransparency = 0.75", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.9 mobile scrollbar auto-hide", function()
		it("applyScrollbarAutoHide helper defined", function()
			expect(clientSource:find("local function applyScrollbarAutoHide(scrollingFrame)", 1, true)).to.be.a("number")
		end)
		it("helper has IS_MOBILE guard", function()
			expect(clientSource:find("if not IS_MOBILE then return end", 1, true)).to.be.a("number")
		end)
		it("helper uses 1.2s idle delay", function()
			expect(clientSource:find("task.delay(1.2", 1, true)).to.be.a("number")
		end)
		it("initial transparency set to 1 (hidden)", function()
			expect(clientSource:find("ScrollBarImageTransparency = 1", 1, true)).to.be.a("number")
		end)
		it("applied to inventoryList", function()
			expect(clientSource:find("applyScrollbarAutoHide(inventoryList)", 1, true)).to.be.a("number")
		end)
		it("applied to collectionList", function()
			expect(clientSource:find("applyScrollbarAutoHide(collectionList)", 1, true)).to.be.a("number")
		end)
		it("applied to shopList", function()
			expect(clientSource:find("applyScrollbarAutoHide(shopList)", 1, true)).to.be.a("number")
		end)
		it("applied to questList", function()
			expect(clientSource:find("applyScrollbarAutoHide(questList)", 1, true)).to.be.a("number")
		end)
		it("applied to raidTargetList", function()
			expect(clientSource:find("applyScrollbarAutoHide(raidTargetList)", 1, true)).to.be.a("number")
		end)
		it("applied to helpList", function()
			expect(clientSource:find("applyScrollbarAutoHide(helpList)", 1, true)).to.be.a("number")
		end)
		it("helper applied to all 6 scrolling frames", function()
			local count = 0
			for _ in clientSource:gmatch("applyScrollbarAutoHide%(") do count = count + 1 end
			expect(count).to.equal(7) -- 1 definition check + 6 calls
		end)
	end)

	describe("kqbq.7 cast overlay zone micro-labels", function()
		it("perfectLabel is defined", function()
			expect(clientSource:find("local perfectLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("perfectLabel text is PERFECT", function()
			expect(clientSource:find('Text = "PERFECT"', 1, true)).to.be.a("number")
		end)
		it("goodLabel is defined", function()
			expect(clientSource:find("local goodLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("goodLabel text is GOOD", function()
			expect(clientSource:find('Text = "GOOD"', 1, true)).to.be.a("number")
		end)
		it("castCountSession counter exists", function()
			expect(clientSource:find("local castCountSession = 0", 1, true)).to.be.a("number")
		end)
		it("progressive disclosure threshold is 5 casts", function()
			expect(clientSource:find("castCountSession <= 5", 1, true)).to.be.a("number")
		end)
		it("full alpha is 0.05 for first casts", function()
			expect(clientSource:find("and 0.05 or 0.45", 1, true)).to.be.a("number")
		end)
		it("settled alpha is 0.45 after 5 casts", function()
			expect(clientSource:find("0.05 or 0.45", 1, true)).to.be.a("number")
		end)
		it("mobile guard hides goodLabel when zone too narrow", function()
			expect(clientSource:find("goodWidth > 0.25", 1, true)).to.be.a("number")
		end)
		it("perfectLabel tracks perfect zone center", function()
			expect(clientSource:find("perfectLabel.Position = UDim2.new", 1, true)).to.be.a("number")
		end)
		it("goodLabel tracks good zone center", function()
			expect(clientSource:find("goodLabel.Position = UDim2.new", 1, true)).to.be.a("number")
		end)
		it("both labels are non-interactive", function()
			expect(clientSource:find("Active = false", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.8 mobile action-stack scroll affordance", function()
		it("stackFade frame exists", function()
			expect(clientSource:find('stackFade.Name = "StackFade"', 1, true)).to.be.a("number")
		end)
		it("stackFade is non-interactive (Active=false)", function()
			expect(clientSource:find("stackFade.Active = false", 1, true)).to.be.a("number")
		end)
		it("stackFade has UIGradient with 90 rotation", function()
			expect(clientSource:find("fadeGrad.Rotation = 90", 1, true)).to.be.a("number")
		end)
		it("stackFade is 24px tall", function()
			expect(clientSource:find("0, 24", 1, true) == nil).to.equal(false) -- 24 exists in the size
		end)
		it("fade transparency sequence exists", function()
			expect(clientSource:find("NumberSequenceKeypoint.new(0, 0.84)", 1, true)).to.be.a("number")
		end)
		it("stackNudged flag for one-time nudge", function()
			expect(clientSource:find("local stackNudged = false", 1, true)).to.be.a("number")
		end)
		it("CanvasPosition watcher exists", function()
			expect(clientSource:find('stack:GetPropertyChangedSignal("CanvasPosition")', 1, true)).to.be.a("number")
		end)
		it("scroll nudge moves 8px", function()
			expect(clientSource:find("origY + 8", 1, true)).to.be.a("number")
		end)
		it("fade hides at scroll bottom", function()
			expect(clientSource:find("stack.CanvasSize.Y.Offset - stack.AbsoluteSize.Y", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.11 HUD income-line split labels", function()
		it("incomeRateLabel exists", function()
			expect(clientSource:find("local incomeRateLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("readyLabel exists", function()
			expect(clientSource:find("local readyLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("old incomeLabel is hidden", function()
			expect(clientSource:find("incomeLabel.Visible = false", 1, true)).to.be.a("number")
		end)
		it("rate label uses AutomaticSize.X", function()
			expect(clientSource:find("AutomaticSize = Enum.AutomaticSize.X", 1, true)).to.be.a("number")
		end)
		it("readyLabel uses claim green Color3", function()
			expect(clientSource:find("Color3.fromRGB(50, 160, 80)", 1, true)).to.be.a("number")
		end)
		it("updateIncomeLine takes no alpha parameter", function()
			expect(clientSource:find("local function updateIncomeLine()", 1, true)).to.be.a("number")
		end)
		it("pulse sets readyLabel.TextTransparency directly", function()
			expect(clientSource:find("readyLabel.TextTransparency = alpha", 1, true)).to.be.a("number")
		end)
		it("readyLabel positioned via TextBounds measurement", function()
			expect(clientSource:find("incomeRateLabel.TextBounds.X", 1, true)).to.be.a("number")
		end)
		it("no RichText format string rebuild remains", function()
			expect(clientSource:find('<font color="#%s" transparency', 1, true) == nil).to.equal(true)
		end)
		it("CLAIM_GREEN_HEX constant removed", function()
			expect(clientSource:find('CLAIM_GREEN_HEX = "32A050"', 1, true) == nil).to.equal(true)
		end)
	end)
end)
end
