-- Client chrome source-contract tests (EPIC 44, harborheist-kqbq).
--
-- init.client.lua cannot be required under lune (Instance/game at top
-- level), so these specs assert the production source still contains the
-- motion/feedback invariants landed by EPIC 44 children. Pure source
-- contracts only — visual confirmation lives in the Studio passes
-- (harborheist-orpl / harborheist-rswb).
--
-- kqbq.1 contracts ACTIVATED 2026-08-01: all four close sites verified at 0.22s.
-- kqbq.2 contracts ACTIVATED 2026-08-01: EASE_PRESS 0.10s, depth 0.94.
-- kqbq.3 contracts ACTIVATED 2026-08-01: EASE_HOVER 0.2s for all hover tweens.
-- kqbq.17.2 contracts: Theme.motion is the single source; presets derive
-- from tokens, Anim:* transitions pass EASE_OUT/EASE_POP.
-- kqbq.5 contracts ACTIVATED 2026-08-01: toast accent bar 6px + soft glow frame.
-- kqbq.6 contracts ACTIVATED 2026-08-01: marker glow 18px / 0.50 transparency.
-- kqbq.9 contracts ACTIVATED 2026-08-01: mobile scrollbar auto-hide on idle.
-- kqbq.7 contracts ACTIVATED 2026-08-01: cast overlay zone micro-labels.
-- kqbq.8 contracts ACTIVATED 2026-08-01: mobile action-stack scroll affordance.
-- kqbq.11 contracts ACTIVATED 2026-08-01: HUD income-line split labels (kill 5Hz RichText rebuild).
-- kqbq.12.2 contracts ACTIVATED 2026-08-01: Esc cancels the cast overlay via Remotes.CancelCast.
-- kqbq.14 contracts ACTIVATED 2026-08-01: empty-state icon tiles (GradientLibrary, category glyphs).
-- kqbq.18.2 contracts ACTIVATED 2026-08-01: uniform disabled treatment (setButtonEnabled helper + debounce/claim/lock fixes).
-- a2ug.12 contracts ACTIVATED 2026-08-01: raid-target best-in-pool intel chip (client half; server half in RaidServiceLogic.spec).
-- kqbq.17.3 contracts ACTIVATED 2026-08-01: panel-open input gating (backdrop tap suppressed during 0.28s open animation).
-- kqbq.10 contracts ACTIVATED 2026-08-01: desktop hover tooltips (ACTION_INFO single source, shared instance, keyboard parity).
-- a2ug.15 contracts ACTIVATED 2026-08-01: wandering-player zone re-guidance (2nd consecutive out-of-zone refusal re-arms the cue).
-- kqbq.22.4 contracts ACTIVATED 2026-08-01: reveal card stroke pulse extended to Rare (dimmer/slower than Epic).
-- kqbq.22.5 contracts ACTIVATED 2026-08-01: GradientLibrary palette reconciliation + HUD gradient seam fix.

local fs = require("@lune/fs")

local clientSource = fs.readFile("src/client/init.client.lua")
local gradientSource = fs.readFile("src/client/GradientLibrary.lua")
local paletteSource = fs.readFile("src/shared/UIPalette.lua")

return function(describe, it, expect)
describe("EPIC 44 client chrome source contracts", function()
	it("spec harness loads and client source is readable", function()
		expect(#clientSource > 1000).to.equal(true)
	end)

	describe("kqbq.1 panel close/open duration harmony", function()
		it("hidePanels mobile slides down via EASE_OUT preset", function()
			expect(clientSource:find('Anim:slide(panel, "down", EASE_OUT)', 1, true)).to.be.a("number")
		end)
		it("hidePanels desktop scales to 0.9 via EASE_OUT preset", function()
			expect(clientSource:find("Anim:scale(panel, fit * 0.9, EASE_OUT)", 1, true)).to.be.a("number")
		end)
		it("showPanel switch mobile slides oldPanel down via EASE_OUT", function()
			expect(clientSource:find('Anim:slide(oldPanel, "down", EASE_OUT)', 1, true)).to.be.a("number")
		end)
		it("showPanel switch desktop scales oldPanel to 0.9 via EASE_OUT", function()
			expect(clientSource:find("Anim:scale(oldPanel, fit * 0.9, EASE_OUT)", 1, true)).to.be.a("number")
		end)
		it("showPanel mobile slides up via EASE_POP preset", function()
			expect(clientSource:find('Anim:slide(panel, "up", EASE_POP)', 1, true)).to.be.a("number")
		end)
		it("showPanel desktop scales via EASE_POP preset", function()
			expect(clientSource:find("Anim:scale(panel, fit, EASE_POP)", 1, true)).to.be.a("number")
		end)
		it("no 0.16s close duration remains on slide-down paths", function()
			expect(clientSource:find('"down", 0.16', 1, true) == nil).to.equal(true)
		end)
		it("no 0.16s close duration remains on scale-to-0.9 paths", function()
			expect(clientSource:find("fit * 0.9, 0.16", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.2 button press feel", function()
		it("Theme.motion.pressIn token defined at 0.10s Quad Out", function()
			expect(clientSource:find("pressIn = { duration = 0.10, style = Enum.EasingStyle.Quad", 1, true)).to.be.a("number")
		end)
		it("EASE_PRESS derives from Theme.motion.pressIn", function()
			expect(clientSource:find("EASE_PRESS = TweenInfo.new(Theme.motion.pressIn.duration", 1, true)).to.be.a("number")
		end)
		it("pressTween uses EASE_PRESS", function()
			expect(clientSource:find("pressTween = EASE_PRESS", 1, true)).to.be.a("number")
		end)
		it("press compression depth is 0.94", function()
			expect(clientSource:find("pressTween, { Scale = 0.94 }", 1, true)).to.be.a("number")
		end)
		it("release still uses EASE_POP (Spring)", function()
			expect(clientSource:find("EASE_POP, { Scale = 1 }", 1, true)).to.be.a("number")
		end)
		it("EASE_PRESS defined exactly once", function()
			local count = 0
			for _ in clientSource:gmatch("EASE_PRESS") do count = count + 1 end
			expect(count).to.equal(2) -- definition + usage at pressTween
		end)
	end)

	describe("kqbq.3 desktop hover pacing", function()
		it("Theme.motion.hoverOut token defined at 0.20s Quad Out", function()
			expect(clientSource:find("hoverOut = { duration = 0.20, style = Enum.EasingStyle.Quad", 1, true)).to.be.a("number")
		end)
		it("EASE_HOVER derives from Theme.motion.hoverOut", function()
			expect(clientSource:find("EASE_HOVER = TweenInfo.new(Theme.motion.hoverOut.duration", 1, true)).to.be.a("number")
		end)
		it("hover scale-up uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { Scale = 1.02 }", 1, true)).to.be.a("number")
		end)
		it("hover color tween uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundColor3 = hoverColor }", 1, true)).to.be.a("number")
		end)
		it("hover glow uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundTransparency = 0.9 }", 1, true)).to.be.a("number")
		end)
		it("hover shadow fade-in uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundTransparency = targetAlpha }", 1, true)).to.be.a("number")
		end)
		it("leave scale-back uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { Scale = 1 }", 1, true)).to.be.a("number")
		end)
		it("leave color restore uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundColor3 = originalColor }", 1, true)).to.be.a("number")
		end)
		it("leave glow hide uses EASE_HOVER", function()
			expect(clientSource:find("EASE_HOVER, { BackgroundTransparency = 1 }", 1, true)).to.be.a("number")
		end)
		it("press path does NOT use EASE_HOVER", function()
			expect(clientSource:find("pressTween = EASE_HOVER", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.5 toast accent bar strengthening", function()
		it("accent bar widened to 6px", function()
			expect(clientSource:find("accentBar.Size = UDim2.new(0, 6, 1, -14)", 1, true)).to.be.a("number")
		end)
		it("accent glow frame exists at ZIndex 56", function()
			expect(clientSource:find("accentGlow.ZIndex = 56", 1, true)).to.be.a("number")
		end)
		it("accent glow is 10px wide", function()
			expect(clientSource:find("accentGlow.Size = UDim2.new(0, 10, 1, -10)", 1, true)).to.be.a("number")
		end)
		it("accent glow fade-in targets 0.85", function()
			expect(clientSource:find("accentGlow, EASE_OUT, { BackgroundTransparency = 0.85 }", 1, true)).to.be.a("number")
		end)
		it("accent glow fade-out targets 1", function()
			expect(clientSource:find("accentGlow, fade, { BackgroundTransparency = 1 }", 1, true)).to.be.a("number")
		end)
		it("no 4px accent bar remains", function()
			expect(clientSource:find("accentBar.Size = UDim2.new(0, 4, 1, -14)", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.6 marker glow brightening", function()
		it("cast/raid marker glow is 18px wide", function()
			expect(clientSource:find("markerGlow.Size = UDim2.new(0, 18, 1, 10)", 1, true)).to.be.a("number")
		end)
		it("cast/raid marker glow transparency is 0.50", function()
			expect(clientSource:find("markerGlow.BackgroundTransparency = 0.50", 1, true)).to.be.a("number")
		end)
		it("bite marker glow is 18px wide", function()
			expect(clientSource:find("biteMarkerGlow.Size = UDim2.new(0, 18, 1, 10)", 1, true)).to.be.a("number")
		end)
		it("bite marker glow transparency is 0.50", function()
			expect(clientSource:find("biteMarkerGlow.BackgroundTransparency = 0.50", 1, true)).to.be.a("number")
		end)
		it("no 0.75 transparency remains on markerGlow", function()
			expect(clientSource:find("markerGlow.BackgroundTransparency = 0.75", 1, true) == nil).to.equal(true)
		end)
		it("no 0.75 transparency remains on biteMarkerGlow", function()
			expect(clientSource:find("biteMarkerGlow.BackgroundTransparency = 0.75", 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.9 mobile scrollbar auto-hide", function()
		it("applyScrollbarAutoHide helper defined", function()
			expect(clientSource:find("local function applyScrollbarAutoHide(scrollingFrame)", 1, true)).to.be.a("number")
		end)
		it("helper has IS_MOBILE guard", function()
			expect(clientSource:find("if not IS_MOBILE then return end", 1, true)).to.be.a("number")
		end)
		it("helper uses 1.2s idle delay", function()
			expect(clientSource:find("task.delay(1.2", 1, true)).to.be.a("number")
		end)
		it("initial transparency set to 1 (hidden)", function()
			expect(clientSource:find("ScrollBarImageTransparency = 1", 1, true)).to.be.a("number")
		end)
		it("applied to inventoryList", function()
			expect(clientSource:find("applyScrollbarAutoHide(inventoryList)", 1, true)).to.be.a("number")
		end)
		it("applied to collectionList", function()
			expect(clientSource:find("applyScrollbarAutoHide(collectionList)", 1, true)).to.be.a("number")
		end)
		it("applied to shopList", function()
			expect(clientSource:find("applyScrollbarAutoHide(shopList)", 1, true)).to.be.a("number")
		end)
		it("applied to questList", function()
			expect(clientSource:find("applyScrollbarAutoHide(questList)", 1, true)).to.be.a("number")
		end)
		it("applied to raidTargetList", function()
			expect(clientSource:find("applyScrollbarAutoHide(raidTargetList)", 1, true)).to.be.a("number")
		end)
		it("applied to helpList", function()
			expect(clientSource:find("applyScrollbarAutoHide(helpList)", 1, true)).to.be.a("number")
		end)
		it("helper applied to all 6 scrolling frames", function()
			local count = 0
			for _ in clientSource:gmatch("applyScrollbarAutoHide%(") do count = count + 1 end
			expect(count).to.equal(7) -- 1 definition check + 6 calls
		end)
	end)

	describe("kqbq.7 cast overlay zone micro-labels", function()
		it("perfectLabel is defined", function()
			expect(clientSource:find("local perfectLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("perfectLabel text is PERFECT", function()
			expect(clientSource:find('Text = "PERFECT"', 1, true)).to.be.a("number")
		end)
		it("goodLabel is defined", function()
			expect(clientSource:find("local goodLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("goodLabel text is GOOD", function()
			expect(clientSource:find('Text = "GOOD"', 1, true)).to.be.a("number")
		end)
		it("castCountSession counter exists", function()
			expect(clientSource:find("local castCountSession = 0", 1, true)).to.be.a("number")
		end)
		it("progressive disclosure threshold is 5 casts", function()
			expect(clientSource:find("castCountSession <= 5", 1, true)).to.be.a("number")
		end)
		it("full alpha is 0.05 for first casts", function()
			expect(clientSource:find("and 0.05 or 0.45", 1, true)).to.be.a("number")
		end)
		it("settled alpha is 0.45 after 5 casts", function()
			expect(clientSource:find("0.05 or 0.45", 1, true)).to.be.a("number")
		end)
		it("mobile guard hides goodLabel when zone too narrow", function()
			expect(clientSource:find("goodWidth > 0.25", 1, true)).to.be.a("number")
		end)
		it("perfectLabel tracks perfect zone center", function()
			expect(clientSource:find("perfectLabel.Position = UDim2.new", 1, true)).to.be.a("number")
		end)
		it("goodLabel tracks good zone center", function()
			expect(clientSource:find("goodLabel.Position = UDim2.new", 1, true)).to.be.a("number")
		end)
		it("both labels are non-interactive", function()
			expect(clientSource:find("Active = false", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.8 mobile action-stack scroll affordance", function()
		it("stackFade frame exists", function()
			expect(clientSource:find('stackFade.Name = "StackFade"', 1, true)).to.be.a("number")
		end)
		it("stackFade is non-interactive (Active=false)", function()
			expect(clientSource:find("stackFade.Active = false", 1, true)).to.be.a("number")
		end)
		it("stackFade has UIGradient with 90 rotation", function()
			expect(clientSource:find("fadeGrad.Rotation = 90", 1, true)).to.be.a("number")
		end)
		it("stackFade is 24px tall", function()
			expect(clientSource:find("0, 24", 1, true) == nil).to.equal(false) -- 24 exists in the size
		end)
		it("fade transparency sequence exists", function()
			expect(clientSource:find("NumberSequenceKeypoint.new(0, 1)", 1, true)).to.be.a("number")
			expect(clientSource:find("NumberSequenceKeypoint.new(1, 0.5)", 1, true)).to.be.a("number")
		end)
		it("stackNudged flag for one-time nudge", function()
			expect(clientSource:find("local stackNudged = false", 1, true)).to.be.a("number")
		end)
		it("CanvasPosition watcher exists", function()
			expect(clientSource:find('stack:GetPropertyChangedSignal("CanvasPosition")', 1, true)).to.be.a("number")
		end)
		it("scroll nudge moves 8px", function()
			expect(clientSource:find("origY + 8", 1, true)).to.be.a("number")
		end)
		it("fade hides at scroll bottom", function()
			expect(clientSource:find("stack.CanvasSize.Y.Offset - stack.AbsoluteSize.Y", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.11 HUD income-line split labels", function()
		it("incomeRateLabel exists", function()
			expect(clientSource:find("local incomeRateLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("readyLabel exists", function()
			expect(clientSource:find("local readyLabel = makeLabel", 1, true)).to.be.a("number")
		end)
		it("old incomeLabel is hidden", function()
			expect(clientSource:find("incomeLabel.Visible = false", 1, true)).to.be.a("number")
		end)
		it("rate label uses AutomaticSize.X", function()
			expect(clientSource:find("AutomaticSize = Enum.AutomaticSize.X", 1, true)).to.be.a("number")
		end)
		it("readyLabel uses claim green Color3", function()
			expect(clientSource:find("Color3.fromRGB(50, 160, 80)", 1, true)).to.be.a("number")
		end)
		it("updateIncomeLine takes no alpha parameter", function()
			expect(clientSource:find("local function updateIncomeLine()", 1, true)).to.be.a("number")
		end)
		it("pulse sets readyLabel.TextTransparency directly", function()
			expect(clientSource:find("readyLabel.TextTransparency = alpha", 1, true)).to.be.a("number")
		end)
		it("readyLabel positioned via TextBounds measurement", function()
			expect(clientSource:find("incomeRateLabel.TextBounds.X", 1, true)).to.be.a("number")
		end)
		it("readyLabel uses TextTruncate.AtEnd (prevents overflow)", function()
			expect(clientSource:find("TextTruncate = Enum.TextTruncate.AtEnd", 1, true)).to.be.a("number")
		end)
		it("readyLabel Size is constrained (no AutomaticSize.X)", function()
			expect(clientSource:find("readyLabel.Size = UDim2.new(1, -(14 + rateW)", 1, true)).to.be.a("number")
		end)
		it("no RichText format string rebuild remains", function()
			expect(clientSource:find('<font color="#%s" transparency', 1, true) == nil).to.equal(true)
		end)
		it("CLAIM_GREEN_HEX constant removed", function()
			expect(clientSource:find('CLAIM_GREEN_HEX = "32A050"', 1, true) == nil).to.equal(true)
		end)
	end)

	describe("kqbq.12.2 Esc cast-overlay cancel (client half of CancelCast)", function()
		it("Esc chain checks the cast overlay only after panel/prompt/onboarding", function()
			expect(clientSource:find('dismissOnboardingPrompt(currentPromptStage)\n\t\telseif isOverlayActive("cast") then', 1, true)).to.be.a("number")
		end)
		it("Esc cancel clears castAwaitingInput first (no coach toast on intentional cancel)", function()
			expect(clientSource:find("castAwaitingInput = false\n\t\t\tstopCastOverlay()", 1, true)).to.be.a("number")
		end)
		it("Esc cancel hides via the standard overlay-release path (stopCastOverlay)", function()
			expect(clientSource:find("castAwaitingInput = false\n\t\t\tstopCastOverlay()\n\t\t\tRemotes.CancelCast:FireServer()", 1, true)).to.be.a("number")
		end)
		it("Esc cancel fires Remotes.CancelCast (server stays authoritative)", function()
			expect(clientSource:find("Remotes.CancelCast:FireServer()", 1, true)).to.be.a("number")
		end)
		it("bite/raid overlays stay non-cancellable (design marker comment)", function()
			expect(clientSource:find("non-cancellable by design", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.14 empty-state iconography upgrade", function()
		it("renderEmptyState cfg includes gradient field", function()
			expect(clientSource:find("gradient = <GradientLibrary", 1, true)).to.be.a("number")
		end)
		it("icon tile Frame is created with 72px size", function()
			expect(clientSource:find("tile.Size = UDim2.new(0, 72, 0, 72)", 1, true)).to.be.a("number")
		end)
		it("tile uses Theme.corners.md for soft corners", function()
			expect(clientSource:find("corner(tile, Theme.corners.md)", 1, true)).to.be.a("number")
		end)
		it("tile has stroke for depth", function()
			expect(clientSource:find("stroke(tile, 0.85, accent, 1)", 1, true)).to.be.a("number")
		end)
		it("Gradients.apply on tile uses cfg.gradient", function()
			expect(clientSource:find('Gradients.apply(tile, cfg.gradient or "accent.soft")', 1, true)).to.be.a("number")
		end)
		it("icon inside tile is 36px (fits the 72px tile)", function()
			expect(clientSource:find("TextSize = 36", 1, true)).to.be.a("number")
		end)
		it("old bare 64px icon size is removed", function()
			expect(clientSource:find("Size = UDim2.new(0, 64, 0, 64)", 1, true) == nil).to.equal(true)
		end)
		it("inventory uses accent.primary gradient", function()
			expect(clientSource:find('gradient = "accent.primary"', 1, true)).to.be.a("number")
		end)
		it("collection uses fish glyph", function()
			expect(clientSource:find('icon = "\\u{1F41F}"', 1, true)).to.be.a("number")
		end)
		it("collection uses status.collection gradient", function()
			expect(clientSource:find('gradient = "status.collection"', 1, true)).to.be.a("number")
		end)
		it("daily quests use calendar glyph", function()
			expect(clientSource:find('icon = "\\u{1F4C5}"', 1, true)).to.be.a("number")
		end)
		it("daily quests use status.warning gradient", function()
			expect(clientSource:find('gradient = "status.warning"', 1, true)).to.be.a("number")
		end)
		it("weekly quests use rotation glyph", function()
			expect(clientSource:find('icon = "\\u{1F504}"', 1, true)).to.be.a("number")
		end)
		it("weekly quests use accent.brand gradient", function()
			expect(clientSource:find('gradient = "accent.brand"', 1, true)).to.be.a("number")
		end)
		it("daily and weekly quest icons are differentiated", function()
			local daily = clientSource:find('icon = "\\u{1F4C5}"', 1, true)
			local weekly = clientSource:find('icon = "\\u{1F504}"', 1, true)
			expect(daily).to.be.a("number")
			expect(weekly).to.be.a("number")
			expect(daily ~= weekly).to.equal(true)
		end)

	describe("kqbq.17.2 Theme.motion centralization", function()
		it("Theme.motion table exists inside Theme constructor", function()
			expect(clientSource:find("motion = {", 1, true)).to.be.a("number")
		end)
		it("easeOut token: 0.22s Quint Out", function()
			expect(clientSource:find("easeOut = { duration = 0.22, style = Enum.EasingStyle.Quint", 1, true)).to.be.a("number")
		end)
		it("pop token: 0.28s Spring Out", function()
			expect(clientSource:find("pop = { duration = 0.28, style = Enum.EasingStyle.Spring", 1, true)).to.be.a("number")
		end)
		it("fast token: 0.12s Quad Out", function()
			expect(clientSource:find("fast = { duration = 0.12, style = Enum.EasingStyle.Quad", 1, true)).to.be.a("number")
		end)
		it("ripple token: 0.35s Quad Out (new preset)", function()
			expect(clientSource:find("ripple = { duration = 0.35, style = Enum.EasingStyle.Quad", 1, true)).to.be.a("number")
		end)
		it("flashTail token: 0.45s Quad In", function()
			expect(clientSource:find("flashTail = { duration = 0.45", 1, true)).to.be.a("number")
		end)
		it("toastFade token: 0.40s Quad In", function()
			expect(clientSource:find("toastFade = { duration = 0.40", 1, true)).to.be.a("number")
		end)
		it("EASE_OUT derives from Theme.motion.easeOut", function()
			expect(clientSource:find("EASE_OUT = TweenInfo.new(Theme.motion.easeOut.duration", 1, true)).to.be.a("number")
		end)
		it("EASE_POP derives from Theme.motion.pop", function()
			expect(clientSource:find("EASE_POP = TweenInfo.new(Theme.motion.pop.duration", 1, true)).to.be.a("number")
		end)
		it("EASE_FAST derives from Theme.motion.fast", function()
			expect(clientSource:find("EASE_FAST = TweenInfo.new(Theme.motion.fast.duration", 1, true)).to.be.a("number")
		end)
		it("EASE_HOVER derives from Theme.motion.hoverOut", function()
			expect(clientSource:find("EASE_HOVER = TweenInfo.new(Theme.motion.hoverOut.duration", 1, true)).to.be.a("number")
		end)
		it("EASE_RIPPLE derives from Theme.motion.ripple", function()
			expect(clientSource:find("EASE_RIPPLE = TweenInfo.new(Theme.motion.ripple.duration", 1, true)).to.be.a("number")
		end)
		it("EASE_IN derives from Theme.motion.easeIn", function()
			expect(clientSource:find("EASE_IN = TweenInfo.new(Theme.motion.easeIn.duration", 1, true)).to.be.a("number")
		end)
		it("ripple call site uses EASE_RIPPLE (not inline literal)", function()
			expect(clientSource:find("TweenService:Create(ripple, EASE_RIPPLE, {", 1, true)).to.be.a("number")
		end)
		it("no inline ripple TweenInfo.new(0.35 remains", function()
			expect(clientSource:find("TweenInfo.new(0.35, Enum.EasingStyle.Quad", 1, true) == nil).to.equal(true)
		end)
		it("toast fade uses Theme.motion.toastFade style", function()
			expect(clientSource:find("Theme.motion.toastFade.style", 1, true)).to.be.a("number")
		end)
		it("flash tail sources from Theme.motion.flashTail", function()
			expect(clientSource:find("Theme.motion.flashTail.duration", 1, true)).to.be.a("number")
		end)
		it("Transitions.durations.fast sourced from Theme.motion", function()
			expect(clientSource:find("fast = Theme.motion.fast.duration", 1, true)).to.be.a("number")
		end)
		it("Transitions.durations.normal sourced from Theme.motion", function()
			expect(clientSource:find("normal = Theme.motion.easeOut.duration", 1, true)).to.be.a("number")
		end)
		it("TOAST_FADE sourced from Theme.motion.toastFade", function()
			expect(clientSource:find("TOAST_FADE = Theme.motion.toastFade.duration", 1, true)).to.be.a("number")
		end)
		it("hidePanels mobile slide passes EASE_OUT", function()
			expect(clientSource:find('Anim:slide(panel, "down", EASE_OUT)', 1, true)).to.be.a("number")
		end)
		it("showPanel mobile slide-up passes EASE_POP", function()
			expect(clientSource:find('Anim:slide(panel, "up", EASE_POP)', 1, true)).to.be.a("number")
		end)
		it("showPanel desktop scale passes EASE_POP", function()
			expect(clientSource:find("Anim:scale(panel, fit, EASE_POP)", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.18.2 uniform disabled treatment", function()
		it("setButtonEnabled helper is defined", function()
			expect(clientSource:find("local setButtonEnabled = function(button, enabled, disabledBg)", 1, true)).to.be.a("number")
		end)
		it("helper saves original colors on first disable", function()
			expect(clientSource:find("kqbq18_2_savedBg", 1, true)).to.be.a("number")
		end)
		it("helper sets Active=false on disable", function()
			expect(clientSource:find('button.Active = false\n\t\tbutton.BackgroundColor3 = disabledBg', 1, true)).to.be.a("number")
		end)
		it("helper restores colors on re-enable", function()
			expect(clientSource:find("button.BackgroundColor3 = savedBg", 1, true)).to.be.a("number")
		end)
		it("helper uses text.tertiary for disabled text color", function()
			expect(clientSource:find("button.TextColor3 = Theme.color.text.tertiary", 1, true)).to.be.a("number")
		end)
		it("debouncedAction uses setButtonEnabled", function()
			expect(clientSource:find("setButtonEnabled(btn, false)", 1, true)).to.be.a("number")
			expect(clientSource:find("setButtonEnabled(btn, true)", 1, true)).to.be.a("number")
		end)
		it("raid opt-in panel button uses setButtonEnabled for debounce", function()
			expect(clientSource:find("setButtonEnabled(raidOptInPanelButton, false)", 1, true)).to.be.a("number")
		end)
		it("raid opt-in aquarium button uses setButtonEnabled for debounce", function()
			expect(clientSource:find("setButtonEnabled(raidOptInButton, false)", 1, true)).to.be.a("number")
		end)
		it("claim button uses setButtonEnabled when not storeHealthy", function()
			expect(clientSource:find("setButtonEnabled(claimButton, false, Theme.color.status.disabled)", 1, true)).to.be.a("number")
		end)
		it("claim button uses setButtonEnabled when healthy", function()
			expect(clientSource:find("setButtonEnabled(claimButton, true)", 1, true)).to.be.a("number")
		end)
		it("lock RECHARGE branch sets Active=false", function()
			expect(clientSource:find('lockClass, lockBg, lockFg = "recharge", Theme.color.surface.elevated, Theme.color.text.tertiary\n\t\tlockButton.Active = false', 1, true)).to.be.a("number")
		end)
		it("lock READY branch sets Active=true", function()
			expect(clientSource:find('lockClass, lockBg, lockFg = "ready", Theme.color.status.warn, Theme.color.text.ink\n\t\tlockButton.Active = true', 1, true)).to.be.a("number")
		end)
		it("lock LOCKED branch sets Active=true (informational, not unavailable)", function()
			expect(clientSource:find('lockClass, lockBg, lockFg = "locked", Theme.color.status.bad, Theme.color.text.ink\n\t\tlockButton.Active = true', 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.18.3 toast text overflow fade-edge", function()
		it("maxTextH overflow threshold computed", function()
			expect(clientSource:find("maxTextH = MIN_TOAST_H", 1, true)).to.be.a("number")
		end)
		it("TextFadeEdge frame created", function()
			expect(clientSource:find('fadeEdge.Name = "TextFadeEdge"', 1, true)).to.be.a("number")
		end)
		it("fade-edge positioned at bottom of toast", function()
			expect(clientSource:find("fadeEdge.Position = UDim2.new(0, 22, 1", 1, true)).to.be.a("number")
		end)
		it("fade-edge has UIGradient with 90 rotation", function()
			expect(clientSource:find("fadeGrad.Rotation = 90", 1, true)).to.be.a("number")
		end)
		it("fade gradient transparency goes 1 to 0", function()
			expect(clientSource:find("NumberSequenceKeypoint.new(0, 1)", 1, true)).to.be.a("number")
			expect(clientSource:find("NumberSequenceKeypoint.new(1, 0)", 1, true)).to.be.a("number")
		end)
		it("fade-edge at ZIndex 59 (above text at 57)", function()
			expect(clientSource:find("fadeEdge.ZIndex = 59", 1, true)).to.be.a("number")
		end)
		it("overflow check uses TextBounds.Y", function()
			expect(clientSource:find("text.TextBounds.Y > maxTextH", 1, true)).to.be.a("number")
		end)
		it("fade-edge fade-in uses EASE_OUT", function()
			expect(clientSource:find("fadeEdge, EASE_OUT", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.15 skip no-op list rebuilds via content signature", function()
		it("lastInventorySignature guard variable is declared", function()
			expect(clientSource:find("local lastInventorySignature = nil", 1, true)).to.be.a("number")
		end)
		it("inventory signature composes maxCarried + fish InstanceIds", function()
			expect(clientSource:find("local signatureParts = { tostring(state.maxCarried or 0) }", 1, true)).to.be.a("number")
		end)
		it("inventory signature includes per-fish InstanceId", function()
			expect(clientSource:find("table.insert(signatureParts, tostring(fish.InstanceId))", 1, true)).to.be.a("number")
		end)
		it("inventory returns early when signature matches", function()
			expect(clientSource:find("if signature == lastInventorySignature then", 1, true)).to.be.a("number")
		end)
		it("inventory stores new signature after rebuild", function()
			expect(clientSource:find("lastInventorySignature = signature", 1, true)).to.be.a("number")
		end)
		it("lastCollectionSignature guard variable is declared", function()
			expect(clientSource:find("local lastCollectionSignature = nil", 1, true)).to.be.a("number")
		end)
		it("collection signature composes discoveredCount + totalSpecies", function()
			expect(clientSource:find('tostring(book.discoveredCount or 0)', 1, true)).to.be.a("number")
			expect(clientSource:find('tostring(book.totalSpecies or 0)', 1, true)).to.be.a("number")
		end)
		it("collection signature folds milestone progress (have/complete/claimed)", function()
			expect(clientSource:find("tostring(milestone.have or 0)", 1, true)).to.be.a("number")
			expect(clientSource:find("milestone.complete and \"1\" or \"0\"", 1, true)).to.be.a("number")
			expect(clientSource:find("milestone.claimed and \"1\" or \"0\"", 1, true)).to.be.a("number")
		end)
		it("collection returns early when signature matches", function()
			expect(clientSource:find("if signature == lastCollectionSignature then", 1, true)).to.be.a("number")
		end)
		it("collection stores new signature after rebuild", function()
			expect(clientSource:find("lastCollectionSignature = signature", 1, true)).to.be.a("number")
		end)
		it("collection signature is reset on panel open (force cached rebuild)", function()
			expect(clientSource:find("lastCollectionSignature = nil\n\t\trenderCollection()", 1, true)).to.be.a("number")
		end)
		it("lastShopSignature guard variable is declared", function()
			expect(clientSource:find("local lastShopSignature = nil", 1, true)).to.be.a("number")
		end)
		it("shop signature iterates all 6 kinds", function()
			expect(clientSource:find('for _, kind in ipairs({ "rod", "bait", "aquarium", "lock", "alarm", "dock" })', 1, true)).to.be.a("number")
		end)
		it("shop signature captures per-kind current level", function()
			expect(clientSource:find("kind .. \":\" .. tostring(currentLevel)", 1, true)).to.be.a("number")
		end)
		it("shop signature captures affordability (Y/N), NOT raw cash", function()
			expect(clientSource:find('affordKey = ((state.cash or 0) >= cost) and "Y" or "N"', 1, true)).to.be.a("number")
		end)
		it("shop signature marks maxed kinds", function()
			expect(clientSource:find('local affordKey = "max"', 1, true)).to.be.a("number")
		end)
		it("shop returns early when signature matches", function()
			expect(clientSource:find("if shopSig == lastShopSignature then", 1, true)).to.be.a("number")
		end)
		it("shop stores new signature after refresh", function()
			expect(clientSource:find("lastShopSignature = shopSig", 1, true)).to.be.a("number")
		end)
		it("no diffing architecture introduced (no keyed row-pooling maps)", function()
			expect(clientSource:find("rowPool", 1, true) == nil).to.equal(true)
		end)
	end)
	end)

	describe("a2ug.12 raid-target best-in-pool intel (client half)", function()
		it("available-row subtitle still carries the stealable count", function()
			expect(clientSource:find('string.format("Dock %d  •  %d stealable fish", target.dockIndex or 0, target.stealableCount or 0)', 1, true)).to.be.a("number")
		end)
		it("chip renders only for available rows with bestRarity", function()
			expect(clientSource:find("if isAvailable and target.bestRarity then", 1, true)).to.be.a("number")
		end)
		it("chip text reads as intel with best-in-pool caption", function()
			expect(clientSource:find('string.format("%s POOL  •  best in pool", string.upper(target.bestRarity))', 1, true)).to.be.a("number")
		end)
		it("chip is rarity-colored via RARITY_COLORS with safe fallback", function()
			expect(clientSource:find("RARITY_COLORS[target.bestRarity] or Theme.color.text.secondary", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.22.4 reveal card stroke pulse extended to Rare", function()
		it("isRarePlus variable includes Rare in the pulse gate", function()
			expect(clientSource:find('local isRarePlus = isEpicPlus or rarity == "Rare"', 1, true)).to.be.a("number")
		end)
		it("isEpicPlus still gates haptic tick (Rare does NOT trigger haptic)", function()
			expect(clientSource:find("if isEpicPlus then\n\t\thapticTick()", 1, true)).to.be.a("number")
		end)
		it("stroke pulse block uses isRarePlus (not isEpicPlus)", function()
			expect(clientSource:find("if isRarePlus then", 1, true)).to.be.a("number")
		end)
		it("Rare pulse period is 0.90s (slower than Epic 0.55s)", function()
			expect(clientSource:find("local pulsePeriod = isEpicPlus and 0.55 or 0.90", 1, true)).to.be.a("number")
		end)
		it("Rare pulse target transparency is 0.25 (dimmer than Epic 0.05)", function()
			expect(clientSource:find("local pulseTarget = isEpicPlus and 0.05 or 0.25", 1, true)).to.be.a("number")
		end)
		it("pulse tween uses Sine InOut with reverse (-1, true)", function()
			expect(clientSource:find("TweenInfo.new(pulsePeriod, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut, -1, true)", 1, true)).to.be.a("number")
		end)
		it("dismiss still cancels revealStrokePulse (Rare pulse joins cancellation)", function()
			expect(clientSource:find("if revealStrokePulse then", 1, true)).to.be.a("number")
			expect(clientSource:find("revealStrokePulse:Cancel()", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.22.5 GradientLibrary palette reconciliation + HUD seam fix", function()
		it("GradientLibrary source is readable", function()
			expect(#gradientSource > 100).to.equal(true)
		end)
		it("no raw Color3.fromRGB( call in GradientLibrary (token discipline)", function()
			expect(gradientSource:find("Color3.fromRGB(", 1, true) == nil).to.equal(true)
		end)
		it("surfaceMid token exists in UIPalette", function()
			expect(paletteSource:find("surfaceMid = { r = 26, g = 38, b = 57 }", 1, true)).to.be.a("number")
		end)
		it("surfaceMid referenced in GradientLibrary UI table", function()
			expect(gradientSource:find('surfaceMid = UIPalette.color("surfaceMid")', 1, true)).to.be.a("number")
		end)
		it("surface.default uses UI.surfaceMid token", function()
			expect(gradientSource:find("default = { from = UI.surfaceMid, to = UI.bg }", 1, true)).to.be.a("number")
		end)
		it("surface.hud uses UI.surface (seam fix — palette-consistent, subtler)", function()
			expect(gradientSource:find("hud = { from = UI.surface, to = UI.bg }", 1, true)).to.be.a("number")
		end)
		it("accent.capacity uses Lerp-derived from color", function()
			expect(gradientSource:find("capacity = { from = UI.purple:Lerp(UI.text, 0.3)", 1, true)).to.be.a("number")
		end)
		it("status.warning from uses UI.quest (was raw 255,205,92 = quest)", function()
			expect(gradientSource:find("warning = { from = UI.quest, to = UI.warn }", 1, true)).to.be.a("number")
		end)
		it("status.success uses Lerp-derived to color", function()
			expect(gradientSource:find("success = { from = UI.good, to = UI.good:Lerp(UI.text, 0.3)", 1, true)).to.be.a("number")
		end)
		it("status.error uses Lerp-derived to color", function()
			expect(gradientSource:find("error = { from = UI.bad, to = UI.bad:Lerp(UI.text, 0.3)", 1, true)).to.be.a("number")
		end)
		it("rarity presets use Lerp-derived colors (no raw fromRGB)", function()
			expect(gradientSource:find("Common = { from = UI.textDim, to = UI.textDim:Lerp(UI.ink, 0.5) }", 1, true)).to.be.a("number")
			expect(gradientSource:find("Legendary = { from = UI.quest, to = UI.quest:Lerp(UI.ink, 0.5) }", 1, true)).to.be.a("number")
		end)
		it("HUD card applies surface.hud gradient", function()
			expect(clientSource:find('Gradients.apply(hud, "surface.hud")', 1, true)).to.be.a("number")
		end)
		it("HUD card base is Theme.color.surface.primary (palette token)", function()
			expect(clientSource:find("hud.BackgroundColor3 = Theme.color.surface.primary", 1, true)).to.be.a("number")
		end)
	end)

	describe("kqbq.10 desktop action-bar hover tooltips", function()
		it("ACTION_INFO single source of truth is declared", function()
			expect(clientSource:find("local ACTION_INFO = {", 1, true)).to.be.a("number")
		end)
		it("ACTION_INFO fish entry carries name + hint + key", function()
			expect(clientSource:find('fish = { name = "Cast Line", hint = "Fish in the glowing zone at your dock", key = "F" },', 1, true)).to.be.a("number")
		end)
		it("ACTION_INFO help entry carries name + hint + key", function()
			expect(clientSource:find('help = { name = "Shortcuts", hint = "Toggle this keyboard-shortcuts panel", key = "H" },', 1, true)).to.be.a("number")
		end)
		it("Theme.motion tooltip token (0.15s Quad Out per kqbq.20.1)", function()
			expect(clientSource:find("tooltip = { duration = 0.15, style = Enum.EasingStyle.Quad, direction = Enum.EasingDirection.Out },", 1, true)).to.be.a("number")
		end)
		it("EASE_TOOLTIP derives from the Theme.motion token", function()
			expect(clientSource:find("local EASE_TOOLTIP = TweenInfo.new(Theme.motion.tooltip.duration, Theme.motion.tooltip.style, Theme.motion.tooltip.direction)", 1, true)).to.be.a("number")
		end)
		it("0.35s hover show delay constant", function()
			expect(clientSource:find("local TOOLTIP_SHOW_DELAY = 0.35", 1, true)).to.be.a("number")
		end)
		it("TOOLTIP_MAX_WIDTH 220 constant (spec hard-cap)", function()
			expect(clientSource:find("local TOOLTIP_MAX_WIDTH = 220", 1, true)).to.be.a("number")
		end)
		it("shared tooltip instance never intercepts the mouse", function()
			expect(clientSource:find("tooltip.Active = false", 1, true)).to.be.a("number")
		end)
		it("suppression predicate covers panel + context menu", function()
			expect(clientSource:find("return activePanel ~= nil or activeContextMenu ~= nil", 1, true)).to.be.a("number")
		end)
		it("suppression predicate covers cast/bite/raid overlays", function()
			expect(clientSource:find('or isOverlayActive("cast") or isOverlayActive("bite") or isOverlayActive("raid")', 1, true)).to.be.a("number")
		end)
		it("keyboard parity polls KeyboardNav:GetFocusedElement", function()
			expect(clientSource:find("KeyboardNav:GetFocusedElement()", 1, true)).to.be.a("number")
		end)
		it("keyboard focus shows immediately (delay 0, no hover wait)", function()
			expect(clientSource:find('scheduleTooltip(focused, "above", focusedInfo.name, focusedInfo.hint, focusedInfo.key, 0)', 1, true)).to.be.a("number")
		end)
		it("HUD card variant carries live income in the hint", function()
			expect(clientSource:find('string.format("Open your aquarium — stored fish earn %s", formatIncomeRate(state and state.incomePerSec or 0))', 1, true)).to.be.a("number")
		end)
		it("SHORTCUT_ROWS action rows re-derived from ACTION_INFO (never drift)", function()
			expect(clientSource:find("table.insert(SHORTCUT_ROWS, actionRowIndex, { key = info.key, desc = info.name })", 1, true)).to.be.a("number")
		end)
		it("positioning clamps X to the viewport", function()
			expect(clientSource:find("math.clamp(centerX - tipW / 2, 8, maxX)", 1, true)).to.be.a("number")
		end)
		it("positioning flips below when space above is short (SAFE_TOP guard)", function()
			expect(clientSource:find("y = btnPos.Y - tipH - TOOLTIP_GAP", 1, true)).to.be.a("number")
			expect(clientSource:find("if y < SAFE_TOP then", 1, true)).to.be.a("number")
		end)
		it("arrow is the 8x8 rotated square from the spec", function()
			expect(clientSource:find("tooltipArrow.Rotation = 45", 1, true)).to.be.a("number")
		end)

	describe("a2ug.15 wandering-player zone re-guidance", function()
		it("zone-refusal handler is forward-declared before showNotification", function()
			expect(clientSource:find("local zoneRefusalHandler = nil", 1, true)).to.be.a("number")
		end)
		it("zone-category toasts increment the refusal streak", function()
			expect(clientSource:find('if category == "zone" and zoneRefusalHandler then', 1, true)).to.be.a("number")
			expect(clientSource:find("zoneRefusalCount = zoneRefusalCount + 1", 1, true)).to.be.a("number")
		end)
		it("re-guidance only arms for post-first-catch wanderers", function()
			expect(clientSource:find("if not state or (state.onboarding or {}).HasCaughtFirstFish ~= true then", 1, true)).to.be.a("number")
		end)
		it("second consecutive refusal is the re-arm threshold", function()
			expect(clientSource:find("if zoneRefusalCount < 2 or zoneCueRearmed then", 1, true)).to.be.a("number")
		end)
		it("never re-arms for dockless players (plaza spawner)", function()
			expect(clientSource:find("if not state.dockIndex then", 1, true)).to.be.a("number")
		end)
		it("re-arm rebuilds the cue and fires the returnToZone prompt", function()
			expect(clientSource:find("zoneCueRearmed = true", 1, true)).to.be.a("number")
			expect(clientSource:find("updateZoneCue(state.dockIndex, false)", 1, true)).to.be.a("number")
			expect(clientSource:find('showOnboardingPrompt("returnToZone", "Follow the arrow back to your glowing zone!", Theme.color.status.warn)', 1, true)).to.be.a("number")
		end)
		it("render() preserves a re-armed cue across state pushes", function()
			expect(clientSource:find("HasCaughtFirstFish == true and not zoneCueRearmed)", 1, true)).to.be.a("number")
		end)
		it("successful cast resets the streak and destroys the re-armed cue via updateZoneCue", function()
			expect(clientSource:find("zoneRefusalCount = 0", 1, true)).to.be.a("number")
			expect(clientSource:find("updateZoneCue(state and state.dockIndex, true)", 1, true)).to.be.a("number")
		end)
	end)
	end)

	describe("kqbq.17.3 panel-open input gating", function()
		it("panelOpening guard flag is declared", function()
			expect(clientSource:find("local panelOpening = false", 1, true)).to.be.a("number")
		end)
		it("panelOpenToken generation counter is declared", function()
			expect(clientSource:find("local panelOpenToken = 0", 1, true)).to.be.a("number")
		end)
		it("showPanel arms the guard before the backdrop is tappable", function()
			expect(clientSource:find("panelOpening = true", 1, true)).to.be.a("number")
		end)
		it("open-complete clear is scheduled on the pop duration", function()
			expect(clientSource:find("task.delay(Theme.motion.pop.duration, function()", 1, true)).to.be.a("number")
		end)
		it("token guard prevents a stale open-clear from dropping the flag", function()
			expect(clientSource:find("if openToken == panelOpenToken then", 1, true)).to.be.a("number")
		end)
		it("hidePanels clears the guard + bumps the token (covers all dismiss paths)", function()
			expect(clientSource:find("panelOpening = false\n\tpanelOpenToken += 1", 1, true)).to.be.a("number")
		end)
		it("backdrop tap is gated on the guard", function()
			expect(clientSource:find("if not panelOpening then", 1, true)).to.be.a("number")
		end)
		it("old direct backdrop.Activated:Connect(hidePanels) is removed", function()
			expect(clientSource:find("backdrop.Activated:Connect(hidePanels)", 1, true) == nil).to.equal(true)
		end)
	end)
end)
end